### ISSUE TITLE
error

### ISSUE THREAD

**Issue by freaky767** [MoronixProduct3/grofit#1]
```(node:12176) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined
    at owners.map (C:\Users\freaky\Desktop\grofit-master\node_modules\discord.js-commando\src\commands\message.js:232:48)
    at Array.map (<anonymous>)
    at CommandMessage.run (C:\Users\freaky\Desktop\grofit-master\node_modules\discord.js-commando\src\commands\message.js:230:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)```

**Comment by MoronixProduct3** [comment]
I am not working on this bot anymore.
Was mostly an experiment. The API must have changed quite a bit since then.
But feel free to post a PR.
